name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install
      run: sudo apt-get install libpoppler-glib-dev
    
    - name: configure
      run: ./configure
      
    - name: Make
      run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
